[2025-06-02T18:16:56.816+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-02T18:16:56.823+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync scheduled__2025-06-01T12:10:00+00:00 [queued]>
[2025-06-02T18:16:56.828+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync scheduled__2025-06-01T12:10:00+00:00 [queued]>
[2025-06-02T18:16:56.828+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-02T18:16:56.840+0530] {taskinstance.py:2888} INFO - Executing <Task(AirbyteJobSensor): wait_for_airbyte_sync> on 2025-06-01 12:10:00+00:00
[2025-06-02T18:16:56.843+0530] {standard_task_runner.py:72} INFO - Started process 55445 to run task
[2025-06-02T18:16:56.847+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airbyte_sync_dag', 'wait_for_airbyte_sync', 'scheduled__2025-06-01T12:10:00+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmpptfbql5i']
[2025-06-02T18:16:56.849+0530] {standard_task_runner.py:105} INFO - Job 260: Subtask wait_for_airbyte_sync
[2025-06-02T18:16:56.883+0530] {task_command.py:467} INFO - Running <TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync scheduled__2025-06-01T12:10:00+00:00 [running]> on host Voldemort.localdomain
[2025-06-02T18:16:56.950+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airbyte_sync_dag' AIRFLOW_CTX_TASK_ID='wait_for_airbyte_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T12:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T12:10:00+00:00'
[2025-06-02T18:16:56.951+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-02T18:16:56.973+0530] {baseoperator.py:405} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2025-06-02T18:16:56.980+0530] {base.py:84} INFO - Retrieving connection 'airbyte_cloud'
[2025-06-02T18:16:57.637+0530] {airbyte.py:87} INFO - Job 38255275 completed successfully.
[2025-06-02T18:16:57.638+0530] {base.py:336} INFO - Success criteria met. Exiting.
[2025-06-02T18:16:57.642+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-02T18:16:57.643+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_dag, task_id=wait_for_airbyte_sync, run_id=scheduled__2025-06-01T12:10:00+00:00, execution_date=20250601T121000, start_date=20250602T124656, end_date=20250602T124657
[2025-06-02T18:16:57.682+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-02T18:16:57.696+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-02T18:16:57.697+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
